[package]
name = "config_macros"
version = "0.1.0"
edition = "2024"
[lib]
proc-macro = true

[dependencies]
syn = "2.0.100"
quote = "1.0.40"
ron = "0.9.0"
serde = { version = "1.0.219", features = ["serde_derive"] }

[dev-dependencies]
trybuild = "1.0"
